apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage-grafana
  resources:
    requests:
      storage: 1Gi
