apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    type: local
    app: grafana
spec:
  storageClassName: local-storage-grafana
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
          path: "/var/lib/grafana"
