apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-claim
  labels:
    app: prometheus-server
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
